name: arkit_plugin_example
description: Demonstrates how to use the arkit_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  arkit_plugin:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/gltf/